answer_index:
    path: /
    methods: GET
    defaults: { _controller: AppBundle:Answer:index }

answer_show:
    path: /{id}
    methods: GET
    defaults: { _controller: AppBundle:Answer:show }

answer_create:
    path: /
    methods: POST
    defaults: { _controller: AppBundle:Answer:create }

answer_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults: { _controller: AppBundle:Answer:update }

answer_upload:
    path: /{id}/upload
    methods: POST
    defaults: { _controller: AppBundle:Answer:upload }

answer_remove:
    path: /{id}
    methods: DELETE
    defaults: { _controller: AppBundle:Answer:remove }
