comment_index:
    path: /
    methods: GET
    defaults: { _controller: AppBundle:Comment:index }

comment_show:
    path: /{id}
    methods: GET
    defaults: { _controller: AppBundle:Comment:show }

comment_create:
    path: /
    methods: POST
    defaults: { _controller: AppBundle:Comment:create }

comment_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults: { _controller: AppBundle:Comment:update }

comment_upload:
    path: /{id}/upload
    methods: POST
    defaults: { _controller: AppBundle:Comment:upload }

comment_remove:
    path: /{id}
    methods: DELETE
    defaults: { _controller: AppBundle:Comment:remove }
